 	create table cafe_manha (
       id int8 generated by default as identity,
        nome varchar(255) not null unique,
        colaborador_id int8,
        primary key (id)
    );
    
    create table colaborador (
       id int8 generated by default as identity,
        cpf varchar(11) not null unique,
        nome varchar(255) not null,
        primary key (id)
    );
    
	alter table if exists cafe_manha 
       add constraint fk_cafe_manha_colaborador_id 
       foreign key (colaborador_id) 
       references colaborador;